---
# Project Information
site_name: libcnb
site_author: Sambhav Kothari
site_description:  Cloud Native Buildpack API bindings for Python

# Repository information
repo_name: samj1912/python-libcnb
repo_url: https://github.com/samj1912/python-libcnb
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Sambhav Kothari

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/samj1912
      name: samj1912 on GitHub

# Page tree
nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      watch:
        - libcnb
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_root_full_path: false
            show_root_toc_entry: false
            show_source: false
            heading_level: 4
            show_signature_annotations: true